import traceback

def handle(name = 'Error'):
    print(traceback.format_exc())
